### ISSUE TITLE
REGARDING BATTERY LIFE

### ISSUE THREAD

**Issue by sai5567** [AswindevSP/Dell-Inspiron-5567-Catalina#1]
Bro how is ur battery life using hackintosh
im getting around 2hrs 
is it normal??

**Comment by AswindevSP** [comment]
Its normal! I am also getting around 2 hours! Its because the power draw frim Intel devices are greater when compared to windows! 


https://www.tonymacx86.com/threads/guide-native-power-management-for-laptops.175801/

**Comment by sai5567** [comment]
Bro how r u using ur work station
Like dual boot windows and hackintosh or purely hackintosh
Im asking this because how can we rely on our battery when we travel which gives atmost 2 hrs of battery life

**Comment by AswindevSP** [comment]
I duel boot Pop os along side catallina. And use shared partition (exfat formate)  to store my data so that i  can access from both os.
