### ISSUE TITLE
REGARDING BATTERY LIFE

### ISSUE THREAD

**Issue by sai5567** [AswindevSP/Dell-Inspiron-5567-Catalina#2]
Hi i too have same laptop as yours which is dell 5567 i7 7th gen
When im using hackintosh but im deeply concerned about the battery life as i only get 1.5 hr to 2 hr maximum
How about yours battery life
Did u do something about ur battery life

**Comment by AswindevSP** [comment]
Use the cpu friend in the repository to make the some kexts according to you need(Lowest core clock=800). Place it in the kexts folder. Maybe it will help. If you do a lot of browsing turn off hardware acceleration from browser settings.

**Comment by sai5567** [comment]
Bro one last question
 how much battery life r u getting in clover 
Recently u posted open core efi what changes did see between them like battery life and performance

**Comment by AswindevSP** [comment]
My battery is almost done. It got like 2 lives in the dell battery manager. I gets around 1 hour 15 min in windows mostly streaming music and videos, nothing intesive. I get the about the same round 1 hour in Big Sur. 

I think open core gives better battery than clover.  Maybe its beacuse i stopped using the internal wifi adapter and switched to a external one. (I switched to extenal beacuse the intel one stopped working.) There is like zero optimation for power conception in intel devices in hackintosh. 

Maybe its beacause of open core maybe it beacuse of changing to extenal wifi adapter. Not really sure.

Btw you should change from clover to open core. Its much better!

**Comment by sai5567** [comment]
Hey man thnx for ur suggestion
My battery is a new one just replaced the old one a week ago but still my battery life sucks 
I spend around 4k rupees for the new battery and my old battery was completely dead and wont charge
 i used to get 4.5 hrs while using ubuntu 20.04 with TLP enabled with new one
so im thinking of going back to ubuntu
Anyway nice chat with you have a great day
